server:
  servlet:
    context-path: /ecom-od
  port: 8090
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_CONNECTION_STRING:jdbc:mysql://localhost:3306/e_order_mgt}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    show-sql: false
    properties:
      hibernate:
        ddl-auto: validate
  flyway:
    enabled: true
    validate-on-migrate: true
app:
  env: dev
  name: ecom-od
